import Head from "next/head";
import styles from "../styles/Home.module.css";

interface LayoutProps {
  children: React.ReactNode;
}

const Layout = ({ children }: LayoutProps) => {
  return (
    <div className={styles.container}>
      <Head>
        <title>PokeDex App</title>
        <meta
          name="description"
          content="PokeDex Generated by create next app"
        />
      </Head>

      <main className={styles.main}>{children}</main>
    </div>
  );
};

export default Layout;
